// Generated from location.config.json. Do not edit this file directly.
export const SENSOR_LOCATION = {
  "id": "goodwin_hall",
  "label": "Goodwin Hall",
  "latitude": 37.2323018,
  "longitude": -80.4259878
} as const;
