// Generated from location.config.json. Do not edit this file directly.
export const SENSOR_LOCATION = {
  "id": "dining_hall_main",
  "label": "Dietrick Hall (D2)",
  "latitude": 37.22455,
  "longitude": -80.41895
} as const;
