-- Campus Crowd: run once in the SQL Editor for project myjfbuathehfghagbnot.
-- The ESP32 inserts aggregate readings using the project's anon key.

create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  avg_rssi real not null,
  packet_count integer not null check (packet_count >= 0),
  density integer not null check (density between 0 and 100),
  location text not null
);

create index if not exists readings_location_created_at_idx
  on public.readings (location, created_at desc);

alter table public.readings enable row level security;

-- The browser dashboard only needs to read aggregate rows.
drop policy if exists "Public can read crowd readings" on public.readings;
create policy "Public can read crowd readings"
  on public.readings for select to anon
  using (true);

-- The ESP32 only inserts; it cannot change or delete readings. This accepts
-- location IDs from location.config.json (lowercase letters, numbers, underscores),
-- so moving the sensor never requires a secret key or an RLS policy edit.
drop policy if exists "Public can insert crowd readings" on public.readings;
create policy "Public can insert crowd readings"
  on public.readings for insert to anon
  with check (
    location ~ '^[a-z][a-z0-9_]{0,63}$'
    and density between 0 and 100
    and packet_count >= 0
  );

grant usage on schema public to anon;
grant select, insert on public.readings to anon;
grant usage, select on sequence public.readings_id_seq to anon;
