-- Campus Crowd: run once in the SQL Editor for project myjfbuathehfghagbnot.
-- The ESP32 inserts aggregate readings using the project's anon key.

create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  avg_rssi real not null,
  packet_count integer not null check (packet_count >= 0),
  density integer not null check (density between 0 and 100),
  location text not null,
  src text not null default 'esp32'
);

alter table public.readings add column if not exists src text not null default 'esp32';

-- Table Editor helper: created_at stays timestamptz (UTC). This is America/New_York wall clock (EDT in summer).
alter table public.readings
  add column if not exists created_at_est timestamp
  generated always as ((created_at at time zone 'America/New_York')) stored;

create index if not exists readings_location_created_at_idx
  on public.readings (location, created_at desc);

alter table public.readings enable row level security;

-- The browser dashboard only needs to read aggregate rows.
drop policy if exists "Public can read crowd readings" on public.readings;
create policy "Public can read crowd readings"
  on public.readings for select to anon
  using (true);

-- The ESP32 only inserts; it cannot change or delete readings. This accepts
-- location IDs from location.config.json (lowercase letters, numbers, underscores),
-- so moving the sensor never requires a secret key or an RLS policy edit.
drop policy if exists "Public can insert crowd readings" on public.readings;
create policy "Public can insert crowd readings"
  on public.readings for insert to anon
  with check (
    location ~ '^[a-z][a-z0-9_]{0,63}$'
    and density between 0 and 100
    and packet_count >= 0
  );

grant usage on schema public to anon;
grant select, insert on public.readings to anon;
grant usage, select on sequence public.readings_id_seq to anon;

-- Ring buffer: keep the newest 2000 ESP32 rows (~18h at 30s windows).
create or replace function public.trim_readings_cap()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cap constant int := 2000;
begin
  -- ponytail: delete oldest extras on each insert; fine while cap is a few thousand.
  delete from public.readings
  where id not in (
    select id from public.readings
    order by created_at desc, id desc
    limit cap
  );
  return null;
end;
$$;

drop trigger if exists readings_trim_cap on public.readings;
create trigger readings_trim_cap
  after insert on public.readings
  for each statement
  execute function public.trim_readings_cap();

-- Fake movement series for charts. Not mixed into live ESP32 readings.
create table if not exists public.sim_readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  avg_rssi real not null,
  packet_count integer not null check (packet_count >= 0),
  density integer not null check (density between 0 and 100),
  location text not null,
  src text not null default 'sim'
);

alter table public.sim_readings add column if not exists src text not null default 'sim';

alter table public.sim_readings
  add column if not exists created_at_est timestamp
  generated always as ((created_at at time zone 'America/New_York')) stored;

create index if not exists sim_readings_location_created_at_idx
  on public.sim_readings (location, created_at desc);

alter table public.sim_readings enable row level security;

drop policy if exists "Public can read sim readings" on public.sim_readings;
create policy "Public can read sim readings"
  on public.sim_readings for select to anon
  using (true);

grant select on public.sim_readings to anon;

-- Seed / wipe: supabase/sim_readings.sql
--   delete from public.sim_readings;
